const defaults=['BD Master','BIR','Dept wise consumption Master','GRN Master updation','Inventory Manager Upd','Item Mapping','Muraqib Updation','PD Demand Master','PO PR Updation','POFU','POFU Reminder','PR WO','Supply Constraint items'];
let tasks=JSON.parse(localStorage.getItem('task-manager-tasks')||'null')||[{id:crypto.randomUUID(),task:'BD Master',frequency:'Every Week',dueDate:'2026-09-28',day:'Monday',done:false}];
let taskOptions=JSON.parse(localStorage.getItem('task-manager-options')||'null')||defaults;
let tatItems=JSON.parse(localStorage.getItem('task-manager-tat')||'[]'); let actionOptions=JSON.parse(localStorage.getItem('task-manager-action-options')||'[]'); let activeClass='All'; let activeStatus='All'; let activeTask=''; let activeDueDate=''; let activeDone='All'; let activeTaskStatus='All';
const $=s=>document.querySelector(s);const format=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'});const safe=v=>{const e=document.createElement('div');e.textContent=v;return e.innerHTML};const date=v=>v?format.format(new Date(v+'T12:00:00')):'';
function renderTaskSuggestions(){ $('#taskSuggestions').innerHTML=taskOptions.map(x=>`<option value="${safe(x)}"></option>`).join(''); }
function dayFromDate(value){return value?new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'UTC'}).format(new Date(value+'T00:00:00')):'';}
function newRecurring(){const dueDate=today();return{id:crypto.randomUUID(),task:'',frequency:'Every Week',dueDate,remarks:'',done:false,blank:true};}
function renderTasks(){const q=$('#taskSearch').value.toLowerCase(),saved=tasks.filter(t=>!t.blank);const filter=$('#taskFilter');filter.innerHTML='<option value="">All tasks</option>'+[...new Set(saved.map(t=>t.task).filter(Boolean))].sort().map(t=>`<option value="${safe(t)}">${safe(t)}</option>`).join('');filter.value=activeTask;const visible=saved.filter(t=>`${t.task} ${t.frequency} ${t.remarks||''}`.toLowerCase().includes(q)&&(!activeTask||t.task===activeTask)&&(!activeDueDate||t.dueDate===activeDueDate)&&(activeDone==='All'||(activeDone==='Yes')===t.done)&&(activeTaskStatus==='All'||(activeTaskStatus==='Completed')===t.done)),blanks=tasks.filter(t=>t.blank),rows=[...visible,...blanks,newRecurring()];renderTaskSuggestions();$('#taskRows').innerHTML=rows.map(t=>`<tr data-recurring-id="${t.id}" class="${t.blank?'blank-row':''}"><td><input class="task-input" data-recurring-field="task" list="taskSuggestions" value="${safe(t.task)}" placeholder="Enter task"></td><td><select class="task-input" data-recurring-field="frequency">${selectOptions(['Every Week','Every Day','Every Month','One time'],t.frequency)}</select></td><td><input class="task-input date-input" data-recurring-field="dueDate" type="date" value="${safe(t.dueDate)}"></td><td><input class="check" type="checkbox" data-recurring-field="done" ${t.done?'checked':''}></td><td><span class="badge ${t.done?'completed':'pending'}">${t.done?'Completed':'Pending'}</span></td><td><input class="task-input" data-recurring-field="remarks" value="${safe(t.remarks||'')}" placeholder="Add remarks"></td><td>${t.blank?'':'<button class="delete" data-task-delete="'+t.id+'">Delete</button>'}</td></tr>`).join('');const done=saved.filter(t=>t.done).length;$('#totalCount').textContent=saved.length;$('#pendingCount').textContent=saved.length-done;$('#completedCount').textContent=done;const next=saved.filter(t=>!t.done&&t.dueDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];$('#nextDue').textContent=next?date(next.dueDate).replace(/ 2026$/,''):'—';}
function today(){const d=new Date();const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10);}
function newTat(){return{id:crypto.randomUUID(),date:today(),description:'',action:'',class:'Timepass',status:'Pending',blank:true};}
function selectOptions(values,current){return values.map(v=>`<option ${v===current?'selected':''}>${safe(v)}</option>`).join('');}
function renderTat(){const saved=tatItems.filter(t=>!t.blank);const filtered=saved.filter(t=>(activeClass==='All'||t.class===activeClass)&&(activeStatus==='All'||t.status===activeStatus));const blankRows=tatItems.filter(t=>t.blank);const rows=[...filtered,...blankRows,newTat()];$('#actionSuggestions').innerHTML=actionOptions.map(x=>`<option value="${safe(x)}"></option>`).join('');$('#tatRows').innerHTML=rows.map(t=>`<tr data-tat-id="${t.id}" class="${t.blank?'blank-row':''}"><td><input class="tat-input date-input" data-field="date" type="date" value="${safe(t.date)}"></td><td><input class="tat-input" data-field="description" value="${safe(t.description)}" placeholder="Enter task description"></td><td><input class="tat-input" data-field="action" list="actionSuggestions" value="${safe(t.action)}" placeholder="Enter what to do"></td><td><select class="tat-input" data-field="class">${selectOptions(['Timepass','ASAP','R & D','FU','-'],t.class)}</select></td><td><select class="tat-input" data-field="status">${selectOptions(['Pending','In progress','Completed'],t.status)}</select></td><td>${t.blank?'':'<button class="delete" data-tat-delete="'+t.id+'">Delete</button>'}</td></tr>`).join('');$('#tatFilterEmpty').hidden=filtered.length>0;}
function persistTat(){localStorage.setItem('task-manager-tat',JSON.stringify(tatItems));}
function addTatRow(){tatItems.push(newTat());persistTat();renderTat();const inputs=$('#tatRows tr:nth-last-child(2) input');if(inputs)inputs.focus();}
function switchTab(tab){const tat=tab==='tat';$('#tasksPanel').hidden=tat;$('#tatPanel').hidden=!tat;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>switchTab(x.dataset.tab));
$('#taskSearch').oninput=renderTasks;$('#taskFilter').onchange=e=>{activeTask=e.target.value;renderTasks();};$('#dueDateFilter').onchange=e=>{activeDueDate=e.target.value;renderTasks();};document.querySelectorAll('.done-slicer').forEach(x=>x.onclick=()=>{activeDone=x.dataset.done;document.querySelectorAll('.done-slicer').forEach(b=>b.classList.toggle('active',b===x));renderTasks();});document.querySelectorAll('.task-status-slicer').forEach(x=>x.onclick=()=>{activeTaskStatus=x.dataset.taskStatus;document.querySelectorAll('.task-status-slicer').forEach(b=>b.classList.toggle('active',b===x));renderTasks();});$('#resetTaskFilters').onclick=()=>{activeTask='';activeDueDate='';activeDone='All';activeTaskStatus='All';$('#taskSearch').value='';$('#dueDateFilter').value='';document.querySelectorAll('.done-slicer,.task-status-slicer').forEach(b=>b.classList.toggle('active',b.dataset.done==='All'||b.dataset.taskStatus==='All'));renderTasks();};$('#addTaskRow').onclick=()=>{tasks.push(newRecurring());localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};$('#taskRows').onchange=e=>{const row=e.target.closest('tr'),id=row?.dataset.recurringId,field=e.target.dataset.recurringField;if(!id||!field)return;let item=tasks.find(t=>t.id===id);if(!item){item={...newRecurring(),id,blank:false};tasks.push(item);}item[field]=field==='done'?e.target.checked:e.target.value;item.blank=false;if(field==='task'&&e.target.value.trim()&&!taskOptions.some(x=>x.toLowerCase()===e.target.value.trim().toLowerCase())){taskOptions.push(e.target.value.trim());localStorage.setItem('task-manager-options',JSON.stringify(taskOptions));}localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};$('#taskRows').onclick=e=>{const id=e.target.dataset.taskDelete;if(!id)return;tasks=tasks.filter(t=>t.id!==id);localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};
$('#addTatRow').onclick=addTatRow;$('#tatRows').onchange=e=>{const row=e.target.closest('tr'),id=row?.dataset.tatId,field=e.target.dataset.field;if(!id||!field)return;let item=tatItems.find(t=>t.id===id);if(!item){item={...newTat(),id,blank:false};tatItems.push(item);}item[field]=e.target.value;item.blank=false;if(field==='action'&&e.target.value.trim()&&!actionOptions.some(x=>x.toLowerCase()===e.target.value.trim().toLowerCase())){actionOptions.push(e.target.value.trim());localStorage.setItem('task-manager-action-options',JSON.stringify(actionOptions));}persistTat();renderTat();};$('#tatRows').onclick=e=>{const id=e.target.dataset.tatDelete;if(!id)return;tatItems=tatItems.filter(t=>t.id!==id);persistTat();renderTat();};document.querySelectorAll('.slicer-button').forEach(x=>x.onclick=()=>{activeClass=x.dataset.class;document.querySelectorAll('.slicer-button').forEach(b=>b.classList.toggle('active',b===x));renderTat();});document.querySelectorAll('.status-slicer-button').forEach(x=>x.onclick=()=>{activeStatus=x.dataset.status;document.querySelectorAll('.status-slicer-button').forEach(b=>b.classList.toggle('active',b===x));renderTat();});
function downloadExcel(items,name){const headers=['Date','Task Description','What to do','Class','Status'];const cells=value=>`<td>${safe(value||'')}</td>`;const table=`<table><thead><tr>${headers.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${items.map(t=>`<tr>${cells(t.date)}${cells(t.description)}${cells(t.action)}${cells(t.class)}${cells(t.status)}</tr>`).join('')}</tbody></table>`;const file=new Blob(['\ufeff<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><body>'+table+'</body></html>'],{type:'application/vnd.ms-excel'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=name;link.click();URL.revokeObjectURL(link.href);}
$('#exportFull').onclick=()=>downloadExcel(tatItems.filter(t=>!t.blank),'TAT-full-list.xls');$('#exportFiltered').onclick=()=>downloadExcel(tatItems.filter(t=>!t.blank&&(activeClass==='All'||t.class===activeClass)&&(activeStatus==='All'||t.status===activeStatus)),'TAT-filtered-list.xls');
renderTaskSuggestions();renderTasks();renderTat();switchTab('tat');
