const defaults=['BD Master','BIR','Dept wise consumption Master','GRN Master updation','Inventory Manager Upd','Item Mapping','Muraqib Updation','PD Demand Master','PO PR Updation','POFU','POFU Reminder','PR WO','Supply Constraint items'];
function withoutFrequency(task){const {frequency,...recurringTask}=task;return recurringTask;}
let tasks=(JSON.parse(localStorage.getItem('task-manager-tasks')||'null')||[{id:crypto.randomUUID(),task:'BD Master',dueDate:'2026-09-28',day:'Monday',done:false}]).map(withoutFrequency);
localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));
let taskOptions=JSON.parse(localStorage.getItem('task-manager-options')||'null')||defaults;
let tatItems=JSON.parse(localStorage.getItem('task-manager-tat')||'[]'); let actionOptions=JSON.parse(localStorage.getItem('task-manager-action-options')||'[]'); let activeClass='All'; let activeStatus='Pending'; let activeTask=''; let activeDueDate=''; let activeDone='All'; let activeTaskStatus='All'; let calendarCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);
const cloudConfig=window.SUPABASE_CONFIG||{}; const cloudReady=cloudConfig.url&&cloudConfig.publishableKey&&!cloudConfig.publishableKey.startsWith('PASTE_'); let cloudSaveTimer;
const $=s=>document.querySelector(s);const format=new Intl.DateTimeFormat('en-GB',{day:'2-digit',month:'short',year:'numeric'});const safe=v=>{const e=document.createElement('div');e.textContent=v;return e.innerHTML};const date=v=>v?format.format(new Date(v+'T12:00:00')):'';
function renderTaskSuggestions(){ $('#taskSuggestions').innerHTML=taskOptions.map(x=>`<option value="${safe(x)}"></option>`).join(''); }
function dayFromDate(value){return value?new Intl.DateTimeFormat('en-US',{weekday:'long',timeZone:'UTC'}).format(new Date(value+'T00:00:00')):'';}
function newRecurring(){const dueDate=today();return{id:crypto.randomUUID(),task:'',dueDate,remarks:'',done:false,blank:true};}
function filteredRecurringTasks(){const q=$('#taskSearch').value.toLowerCase();return tasks.filter(t=>!t.blank&&`${t.task} ${t.remarks||''}`.toLowerCase().includes(q)&&(!activeTask||t.task===activeTask)&&(!activeDueDate||t.dueDate===activeDueDate)&&(activeDone==='All'||(activeDone==='Yes')===t.done)&&(activeTaskStatus==='All'||(activeTaskStatus==='Completed')===t.done));}
function renderTasks(){const saved=tasks.filter(t=>!t.blank);const filter=$('#taskFilter');filter.innerHTML='<option value="">All tasks</option>'+[...new Set(saved.map(t=>t.task).filter(Boolean))].sort().map(t=>`<option value="${safe(t)}">${safe(t)}</option>`).join('');filter.value=activeTask;const visible=filteredRecurringTasks(),blanks=tasks.filter(t=>t.blank),rows=[...visible,...blanks,newRecurring()];renderTaskSuggestions();$('#taskRows').innerHTML=rows.map(t=>`<tr data-recurring-id="${t.id}" class="${t.blank?'blank-row':''}"><td><input class="task-input" data-recurring-field="task" list="taskSuggestions" value="${safe(t.task)}" placeholder="Enter task"></td><td><input class="task-input date-input" data-recurring-field="dueDate" type="date" value="${safe(t.dueDate)}"></td><td><input class="check" type="checkbox" data-recurring-field="done" ${t.done?'checked':''}></td><td><span class="badge ${t.done?'completed':'pending'}">${t.done?'Completed':'Pending'}</span></td><td><input class="task-input" data-recurring-field="remarks" value="${safe(t.remarks||'')}" placeholder="Add remarks"></td><td>${t.blank?'':'<button class="delete" data-task-delete="'+t.id+'">Delete</button>'}</td></tr>`).join('');const done=saved.filter(t=>t.done).length;$('#totalCount').textContent=saved.length;$('#pendingCount').textContent=saved.length-done;$('#completedCount').textContent=done;const next=saved.filter(t=>!t.done&&t.dueDate).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))[0];$('#nextDue').textContent=next?date(next.dueDate).replace(/ 2026$/,''):'—';}
function today(){const d=new Date();const offset=d.getTimezoneOffset();return new Date(d.getTime()-offset*60000).toISOString().slice(0,10);}
function newTat(){return{id:crypto.randomUUID(),date:today(),description:'',action:'',class:'Timepass',status:'Pending',blank:true};}
function selectOptions(values,current){return values.map(v=>`<option ${v===current?'selected':''}>${safe(v)}</option>`).join('');}
function autoSizeTatDescriptions(scope=document){scope.querySelectorAll('.tat-description').forEach(field=>{field.style.height='auto';field.style.height=`${field.scrollHeight}px`;});}
function renderTat(){const saved=tatItems.filter(t=>!t.blank);const filtered=saved.filter(t=>(activeClass==='All'||t.class===activeClass)&&(activeStatus==='All'||t.status===activeStatus));const blankRows=tatItems.filter(t=>t.blank);const rows=[...filtered,...blankRows,newTat()];$('#actionSuggestions').innerHTML=actionOptions.map(x=>`<option value="${safe(x)}"></option>`).join('');$('#tatRows').innerHTML=rows.map(t=>`<tr data-tat-id="${t.id}" class="${t.blank?'blank-row':''}"><td><input class="tat-input date-input" data-field="date" type="date" value="${safe(t.date)}"></td><td class="description-cell"><textarea class="tat-input tat-description" data-field="description" rows="1" placeholder="Enter task description">${safe(t.description)}</textarea></td><td><input class="tat-input" data-field="action" list="actionSuggestions" value="${safe(t.action)}" placeholder="Enter what to do"></td><td><select class="tat-input" data-field="class">${selectOptions(['Timepass','ASAP','R & D','FU','-'],t.class)}</select></td><td><select class="tat-input" data-field="status">${selectOptions(['Pending','In progress','Completed'],t.status)}</select></td><td>${t.blank?'':'<div class="tat-actions"><button class="done" data-tat-done="'+t.id+'" type="button" title="Mark as completed" aria-label="Mark task as completed">Done</button><button class="delete" data-tat-delete="'+t.id+'" type="button" title="Delete task" aria-label="Delete task">Delete</button></div>'}</td></tr>`).join('');autoSizeTatDescriptions($('#tatRows'));$('#tatFilterEmpty').hidden=filtered.length>0;}
function persistTat(){localStorage.setItem('task-manager-tat',JSON.stringify(tatItems));}
function addTatRow(){tatItems.push(newTat());persistTat();renderTat();const inputs=$('#tatRows tr:nth-last-child(2) input');if(inputs)inputs.focus();}
function calendarDateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function calendarDateFromKey(value){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value||'');return match?new Date(Number(match[1]),Number(match[2])-1,Number(match[3])):null;}
function isScheduledOn(task,d){
 // The due date is the source of truth for the calendar; tasks appear only on
 // the date the user explicitly schedules.
 return Boolean(calendarDateFromKey(task.dueDate))&&calendarDateKey(d)===task.dueDate;
}
function renderCalendar(){const year=calendarCursor.getFullYear(),month=calendarCursor.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay()),todayKey=today();$('#calendarMonth').textContent=new Intl.DateTimeFormat('en-US',{month:'long',year:'numeric'}).format(first);$('#calendarGrid').innerHTML=Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);const dayTasks=tasks.filter(t=>!t.blank&&isScheduledOn(t,d));const outside=d.getMonth()!==month;return `<article class="calendar-day ${outside?'outside-month':''} ${calendarDateKey(d)===todayKey?'today':''}"><div><b>${d.getDate()}</b>${dayTasks.length?`<span>${dayTasks.length}</span>`:''}</div>${dayTasks.map(t=>`<button class="calendar-task ${t.done?'done':''}" data-calendar-task="${safe(t.id)}" type="button" title="${safe(`${t.task||'Untitled task'} — ${t.done?'Completed':'Due'} ${calendarDateKey(d)}`)}">${safe(t.task||'Untitled task')}</button>`).join('')}</article>`;}).join('');}
function switchTab(tab,selected=tab){$('#dashboardPanel').hidden=tab!=='dashboard';$('#calendarPanel').hidden=tab!=='calendar';$('#tasksPanel').hidden=tab!=='tasks';$('#tatPanel').hidden=tab!=='tat';document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.nav===selected));if(tab==='dashboard')renderDashboard();if(tab==='calendar')renderCalendar();}
document.querySelectorAll('.tab').forEach(x=>x.onclick=()=>switchTab(x.dataset.tab,x.dataset.nav));
$('#calendarPrev').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar();};$('#calendarNext').onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar();};$('#calendarToday').onclick=()=>{calendarCursor=new Date(new Date().getFullYear(),new Date().getMonth(),1);renderCalendar();};$('#calendarGrid').onclick=e=>{if(e.target.closest('[data-calendar-task]'))switchTab('tasks');};
$('#globalSearch').oninput=e=>{const query=e.target.value.trim().toLowerCase();if(!query)return;const taskMatch=tasks.some(t=>`${t.task} ${t.remarks||''}`.toLowerCase().includes(query));if(taskMatch){$('#taskSearch').value=e.target.value;renderTasks();switchTab('tasks');return;}const tatMatch=tatItems.some(t=>`${t.description} ${t.action||''}`.toLowerCase().includes(query));if(tatMatch){activeClass='All';activeStatus='All';document.querySelectorAll('.slicer-button,.status-slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.class==='All'||b.dataset.status==='All'));renderTat();switchTab('tat');}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#globalSearch').focus();}});
$('#taskSearch').oninput=renderTasks;$('#taskFilter').onchange=e=>{activeTask=e.target.value;renderTasks();};$('#dueDateFilter').onchange=e=>{activeDueDate=e.target.value;renderTasks();};document.querySelectorAll('.done-slicer').forEach(x=>x.onclick=()=>{activeDone=x.dataset.done;document.querySelectorAll('.done-slicer').forEach(b=>b.classList.toggle('active',b===x));renderTasks();});document.querySelectorAll('.task-status-slicer').forEach(x=>x.onclick=()=>{activeTaskStatus=x.dataset.taskStatus;document.querySelectorAll('.task-status-slicer').forEach(b=>b.classList.toggle('active',b===x));renderTasks();});$('#resetTaskFilters').onclick=()=>{activeTask='';activeDueDate='';activeDone='All';activeTaskStatus='All';$('#taskSearch').value='';$('#dueDateFilter').value='';document.querySelectorAll('.done-slicer,.task-status-slicer').forEach(b=>b.classList.toggle('active',b.dataset.done==='All'||b.dataset.taskStatus==='All'));renderTasks();};$('#addTaskRow').onclick=()=>{tasks.push(newRecurring());localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};$('#taskRows').onchange=e=>{const row=e.target.closest('tr'),id=row?.dataset.recurringId,field=e.target.dataset.recurringField;if(!id||!field)return;let item=tasks.find(t=>t.id===id);if(!item){item={...newRecurring(),id,blank:false};tasks.push(item);}item[field]=field==='done'?e.target.checked:e.target.value;item.blank=false;if(field==='task'&&e.target.value.trim()&&!taskOptions.some(x=>x.toLowerCase()===e.target.value.trim().toLowerCase())){taskOptions.push(e.target.value.trim());localStorage.setItem('task-manager-options',JSON.stringify(taskOptions));}localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};$('#taskRows').onclick=e=>{const id=e.target.dataset.taskDelete;if(!id)return;tasks=tasks.filter(t=>t.id!==id);localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();};
$('#addTatRow').onclick=addTatRow;$('#tatRows').oninput=e=>{if(e.target.matches('.tat-description'))autoSizeTatDescriptions(e.target.parentElement);};$('#tatRows').onchange=e=>{const row=e.target.closest('tr'),id=row?.dataset.tatId,field=e.target.dataset.field;if(!id||!field)return;let item=tatItems.find(t=>t.id===id);if(!item){item={...newTat(),id,blank:false};tatItems.push(item);}item[field]=e.target.value;item.blank=false;if(field==='action'&&e.target.value.trim()&&!actionOptions.some(x=>x.toLowerCase()===e.target.value.trim().toLowerCase())){actionOptions.push(e.target.value.trim());localStorage.setItem('task-manager-action-options',JSON.stringify(actionOptions));}persistTat();renderTat();};$('#tatRows').onclick=e=>{const doneId=e.target.closest('[data-tat-done]')?.dataset.tatDone;if(doneId){const item=tatItems.find(t=>t.id===doneId);if(item){item.status='Completed';item.blank=false;persistTat();renderTat();}return;}const id=e.target.closest('[data-tat-delete]')?.dataset.tatDelete;if(!id)return;tatItems=tatItems.filter(t=>t.id!==id);persistTat();renderTat();};document.querySelectorAll('.slicer-button').forEach(x=>x.onclick=()=>{activeClass=x.dataset.class;document.querySelectorAll('.slicer-button').forEach(b=>b.classList.toggle('active',b===x));renderTat();});document.querySelectorAll('.status-slicer-button').forEach(x=>x.onclick=()=>{activeStatus=x.dataset.status;document.querySelectorAll('.status-slicer-button').forEach(b=>b.classList.toggle('active',b===x));renderTat();});
function downloadExcel(items,name){const headers=['Date','Task Description','What to do','Class','Status'];const cells=value=>`<td>${safe(value||'')}</td>`;const table=`<table><thead><tr>${headers.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${items.map(t=>`<tr>${cells(t.date)}${cells(t.description)}${cells(t.action)}${cells(t.class)}${cells(t.status)}</tr>`).join('')}</tbody></table>`;const file=new Blob(['\ufeff<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><body>'+table+'</body></html>'],{type:'application/vnd.ms-excel'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=name;link.click();URL.revokeObjectURL(link.href);}
$('#exportFull').onclick=()=>downloadExcel(tatItems.filter(t=>!t.blank),'TAT-full-list.xls');$('#exportFiltered').onclick=()=>downloadExcel(tatItems.filter(t=>!t.blank&&(activeClass==='All'||t.class===activeClass)&&(activeStatus==='All'||t.status===activeStatus)),'TAT-filtered-list.xls');
function downloadRecurringExcel(items,name){const headers=['Task','Due date','Done','Status','Remarks'],cells=value=>`<td>${safe(value||'')}</td>`;const table=`<table><thead><tr>${headers.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${items.map(t=>`<tr>${cells(t.task)}${cells(t.dueDate)}${cells(t.done?'Yes':'No')}${cells(t.done?'Completed':'Pending')}${cells(t.remarks)}</tr>`).join('')}</tbody></table>`;const file=new Blob(['\ufeff<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><body>'+table+'</body></html>'],{type:'application/vnd.ms-excel'});const link=document.createElement('a');link.href=URL.createObjectURL(file);link.download=name;link.click();URL.revokeObjectURL(link.href);}
$('#exportRecurringFull').onclick=()=>downloadRecurringExcel(tasks.filter(t=>!t.blank),'recurring-tasks-full-list.xls');$('#exportRecurringFiltered').onclick=()=>downloadRecurringExcel(filteredRecurringTasks(),'recurring-tasks-filtered-list.xls');
function importedDate(value){const text=String(value??'').trim();if(!text)return today();if(/^\d{4}-\d{2}-\d{2}$/.test(text))return text;const parts=/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/.exec(text);if(parts){const [,day,month,year]=parts;return `${year}-${month.padStart(2,'0')}-${day.padStart(2,'0')}`;}const parsed=new Date(text);return Number.isNaN(parsed.valueOf())?today():`${parsed.getFullYear()}-${String(parsed.getMonth()+1).padStart(2,'0')}-${String(parsed.getDate()).padStart(2,'0')}`;}
function importRecurringRows(rows){const normalized=rows.map(row=>Object.fromEntries(Object.entries(row).map(([key,value])=>[key.toLowerCase().replace(/\s+/g,''),value])));const imported=normalized.map(row=>{const task=String(row.task??'').trim();const done=/^(yes|true|1|completed)$/i.test(String(row.done??row.status??''));return {id:crypto.randomUUID(),task,dueDate:importedDate(row.duedate),remarks:String(row.remarks??'').trim(),done,blank:false};}).filter(task=>task.task);const known=new Set(tasks.filter(task=>!task.blank).map(task=>[task.task,task.dueDate].join('\u0001')));const additions=imported.filter(task=>{const key=[task.task,task.dueDate].join('\u0001');if(known.has(key))return false;known.add(key);return true;});tasks.push(...additions);additions.forEach(task=>{if(!taskOptions.some(option=>option.toLowerCase()===task.task.toLowerCase()))taskOptions.push(task.task);});localStorage.setItem('task-manager-options',JSON.stringify(taskOptions));localStorage.setItem('task-manager-tasks',JSON.stringify(tasks));renderTasks();renderDashboard();renderCalendar();return {added:additions.length,skipped:imported.length-additions.length,invalid:rows.length-imported.length};}
$('#importRecurringFile').onchange=async event=>{const file=event.target.files?.[0],result=$('#recurringImportResult');event.target.value='';if(!file)return;result.classList.remove('error');result.textContent='Importing…';try{if(!window.XLSX)throw new Error('The Excel importer could not be loaded. Check your internet connection and try again.');const workbook=XLSX.read(await file.arrayBuffer(),{type:'array'}),sheet=workbook.Sheets[workbook.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{defval:'',raw:false});if(!rows.length)throw new Error('The selected file has no task rows.');const summary=importRecurringRows(rows);result.textContent=`Imported ${summary.added} task${summary.added===1?'':'s'}${summary.skipped?`; ${summary.skipped} matching row${summary.skipped===1?' was':'s were'} skipped`:''}${summary.invalid?`; ${summary.invalid} row${summary.invalid===1?' was':'s were'} missing a task name`:''}.`;}catch(error){result.classList.add('error');result.textContent=error.message||'The file could not be imported. Please use the exported recurring-task format.';}};
const nativeSetItem=localStorage.setItem.bind(localStorage);
function renderDashboard(){
 const recurring=tasks.filter(t=>!t.blank), tat=tatItems.filter(t=>!t.blank), all=[...recurring,...tat];
 const completed=recurring.filter(t=>t.done).length+tat.filter(t=>t.status==='Completed').length, open=all.length-completed, percent=all.length?Math.round(completed/all.length*100):0, asap=tat.filter(t=>t.class==='ASAP'&&t.status!=='Completed').length;
 $('#dashTotal').textContent=all.length;$('#dashOpen').textContent=open;$('#dashDone').textContent=completed;$('#dashAsap').textContent=asap;$('#dashRecurring').textContent=recurring.filter(t=>!t.done).length;
 $('#dashTotalNote').textContent=`${recurring.length} recurring · ${tat.length} TAT`;$('#dashOpenNote').textContent=open?`${asap?'Includes '+asap+' ASAP item'+(asap>1?'s':''):'No urgent items flagged'}`:'Everything is completed';$('#dashDoneNote').textContent=`${percent}% overall completion`;
 const now=new Date(), weekday=new Intl.DateTimeFormat('en-US',{weekday:'short'}), dates=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-6+i);return d});
 const values=dates.map(d=>{const key=d.toISOString().slice(0,10);return tat.filter(x=>x.status==='Completed'&&x.date===key).length+recurring.filter(x=>x.done&&x.dueDate===key).length}); const max=Math.max(3,...values); const points=values.map((v,i)=>`${i*(640/6)},${180-v/max*125}`).join(' '); const area=`0,190 ${points} 640,190`;
 $('#activityChart').innerHTML=`<defs><linearGradient id="areaFill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#30a7ff" stop-opacity=".42"/><stop offset="1" stop-color="#30a7ff" stop-opacity="0"/></linearGradient></defs><path d="M0 55H640M0 118H640M0 181H640" class="grid-lines"/><polygon points="${area}" fill="url(#areaFill)"/><polyline points="${points}" class="chart-line"/>${values.map((v,i)=>`<circle cx="${i*(640/6)}" cy="${180-v/max*125}" r="5" class="chart-point"><title>${v} completed</title></circle>`).join('')}`;
 $('#chartLabels').innerHTML=dates.map((d,i)=>`<span>${weekday.format(d)}<b>${values[i]}</b></span>`).join('');
 $('#focusScore').textContent=percent+'%';const circ=301.6;$('#focusRing').style.strokeDasharray=`${circ}`;$('#focusRing').style.strokeDashoffset=`${circ*(1-percent/100)}`;$('#healthLabel').textContent=percent>=75?'On track':percent>=40?'In motion':'Getting started';$('#focusNote').textContent=all.length?`${completed} of ${all.length} tracked item${all.length===1?'':'s'} are complete.`:'Add a task to start building your workflow score.';
 const groups=['ASAP','R & D','FU','Timepass','-'].map(name=>({name,count:tat.filter(t=>t.class===name&&t.status!=='Completed').length})).filter(x=>x.count);$('#classBreakdown').innerHTML=groups.length?groups.map((g,i)=>`<div class="class-row"><span class="class-dot dot-${i}"></span><b>${g.name==='-'?'Other':g.name}</b><div class="bar"><i style="width:${g.count/Math.max(...groups.map(x=>x.count))*100}%"></i></div><strong>${g.count}</strong></div>`).join(''):'<div class="dashboard-empty">No open TAT work. You are clear.</div>';
 const priority=[...tat.filter(t=>t.status!=='Completed').sort((a,b)=>({ASAP:0,FU:1,'R & D':2,Timepass:3,'-':4}[a.class]??5)-({ASAP:0,FU:1,'R & D':2,Timepass:3,'-':4}[b.class]??5)),...recurring.filter(t=>!t.done).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999'))].slice(0,4);$('#priorityQueue').innerHTML=priority.length?priority.map(t=>{const label=t.description||t.task||'Untitled task', meta=t.class?`${t.class} · ${t.status}`:t.dueDate?date(t.dueDate):'No date';return `<div class="priority-item"><span class="priority-mark ${t.class==='ASAP'?'urgent':''}">${t.class==='ASAP'?'!':'•'}</span><div><strong>${safe(label)}</strong><small>${safe(meta)}</small></div></div>`}).join(''):'<div class="dashboard-empty">No unfinished work — enjoy the clear runway.</div>';
 const todayKey=today(), todayTasks=recurring.filter(t=>!t.done&&t.dueDate===todayKey), overdueTasks=recurring.filter(t=>!t.done&&t.dueDate&&t.dueDate<todayKey).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));
 const renderDueList=(items,target,empty)=>{$(target).innerHTML=items.length?items.map(t=>`<div class="dashboard-task"><span class="calendar-icon">□</span><div><strong>${safe(t.task||'Untitled task')}</strong><small>${date(t.dueDate)}</small></div><button class="queue-open" data-go="tasks" type="button">View</button></div>`).join(''):`<div class="dashboard-empty">${empty}</div>`;};
 $('#todayCount').textContent=todayTasks.length;$('#overdueCount').textContent=overdueTasks.length;renderDueList(todayTasks,'#todayList','No pending recurring tasks are due today.');renderDueList(overdueTasks,'#overdueList','No overdue recurring tasks. Great work.');
 const classNames=['ASAP','FU','R & D','Timepass','-'], activeTat=tat.filter(t=>t.status==='Pending'||t.status==='In progress');
 $('#tatClassQueues').innerHTML=classNames.map(className=>{const items=activeTat.filter(t=>t.class===className), label=className==='-'?'Other':className, queueClass=({'ASAP':'asap-queue','FU':'fu-queue','R & D':'rnd-queue','Timepass':'timepass-queue','-':'other-queue'})[className];return `<article class="tat-class-queue ${queueClass}"><button class="tat-class-header" data-tat-class="${safe(className)}" type="button" title="View pending ${safe(label)} tasks in TAT"><span>${safe(label)}</span><b>${items.length}</b></button>${items.length?`<div class="tat-class-items">${items.map(t=>`<div class="tat-class-item"><strong>${safe(t.description||'Untitled task')}</strong><small>${safe(t.action||'No action added')} · <em class="${t.status==='In progress'?'in-progress':''}">${safe(t.status)}</em></small></div>`).join('')}</div>`:'<p class="class-empty">No active items</p>'}</article>`;}).join('');
 $('#dashboardDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'short'}).format(now);$('#commandDate').textContent=new Intl.DateTimeFormat('en-GB',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(now);$('#commandTime').textContent=new Intl.DateTimeFormat('en-US',{hour:'2-digit',minute:'2-digit'}).format(now);$('#dashboardGreeting').textContent=open?`You have ${open} open item${open===1?'':'s'} — focus on what moves forward today.`:'Everything is complete. A great time to plan the next win.';
}
function renderAll(){renderTaskSuggestions();renderTasks();renderTat();renderDashboard();renderCalendar();switchTab('dashboard');}
function queueCloudSave(){if(!cloudReady)return;clearTimeout(cloudSaveTimer);cloudSaveTimer=setTimeout(async()=>{try{await fetch(cloudConfig.url+'/rest/v1/task_manager_data?on_conflict=id',{method:'POST',headers:{apikey:cloudConfig.publishableKey,Authorization:'Bearer '+cloudConfig.publishableKey,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates'},body:JSON.stringify({id:'shared-task-manager',category:'shared',payload:{tasks,taskOptions,tatItems,actionOptions},updated_at:new Date().toISOString()})});}catch(error){console.warn('Cloud save failed. Changes remain on this device.',error);}},450);}
localStorage.setItem=(key,value)=>{nativeSetItem(key,value);if(['task-manager-tasks','task-manager-options','task-manager-tat','task-manager-action-options'].includes(key))queueCloudSave();};
async function loadCloud(){if(!cloudReady)return;try{const response=await fetch(cloudConfig.url+'/rest/v1/task_manager_data?id=eq.shared-task-manager&select=payload',{headers:{apikey:cloudConfig.publishableKey,Authorization:'Bearer '+cloudConfig.publishableKey}});const data=await response.json();if(data?.[0]?.payload){const cloud=data[0].payload;tasks=(cloud.tasks||tasks).map(withoutFrequency);taskOptions=cloud.taskOptions||taskOptions;tatItems=cloud.tatItems||tatItems;actionOptions=cloud.actionOptions||actionOptions;nativeSetItem('task-manager-tasks',JSON.stringify(tasks));nativeSetItem('task-manager-options',JSON.stringify(taskOptions));nativeSetItem('task-manager-tat',JSON.stringify(tatItems));nativeSetItem('task-manager-action-options',JSON.stringify(actionOptions));queueCloudSave();}else{queueCloudSave();}}catch(error){console.warn('Cloud data could not be loaded. Using this device data.',error);}renderAll();}
const resetTatFilters=document.createElement('button');resetTatFilters.id='resetTatFilters';resetTatFilters.type='button';resetTatFilters.className='secondary reset-filters';resetTatFilters.textContent='Reset filters';resetTatFilters.onclick=()=>{activeClass='All';activeStatus='Pending';document.querySelectorAll('.slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.class==='All'));document.querySelectorAll('.status-slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.status==='Pending'));renderTat();};document.querySelector('.export-actions').prepend(resetTatFilters);
document.querySelectorAll('.status-slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.status===activeStatus));document.addEventListener('click',e=>{const classButton=e.target.closest('[data-tat-class]');if(classButton){activeClass=classButton.dataset.tatClass;activeStatus='Pending';document.querySelectorAll('.slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.class===activeClass));document.querySelectorAll('.status-slicer-button').forEach(b=>b.classList.toggle('active',b.dataset.status===activeStatus));renderTat();switchTab('tat');return;}const button=e.target.closest('[data-go]');if(button)switchTab(button.dataset.go);});
renderAll();loadCloud();
